language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mfshair01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mfshair01/react-test npm test

after_success:
  - docker build -t mfshair01/multi-client ./client
  - docker build -t mfshair01/multi-nginx ./nginx
  - docker build -t mfshair01/multi-server ./server
  - docker build -t mfshair01/multi-worker ./worker
  