language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mfshair01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mfshair01/react-test npm test

after_success:
  - docker build -t mfshair01/multi-client ./client
  - docker build -t mfshair01/multi-nginx ./nginx
  - docker build -t mfshair01/multi-server ./server
  - docker build -t mfshair01/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mfshair01/multi-client
  - docker push mfshair01/multi-nginx
  - docker push mfshair01/multi-server
  - docker push mfshair01/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multi-docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-295550966758'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY